import { Project } from '@/types'

export const projects: Project[] = [
  {
    id: '1',
    slug: 'comsim',
    title: 'ComSim',
    shortDescription: 'An interactive educational mobile application designed to help users learn about computer hardware components and PC building through simulation and interactive modules.',
    fullDescription: 'ComSim is an interactive educational mobile application built with React Native and Expo. It helps users learn about computer hardware components and PC building through simulation and interactive modules. Whether you\'re a beginner looking to understand PC components or an enthusiast wanting to test configurations, ComSim provides an engaging platform to explore, learn, and build virtual PCs.',
    category: 'Educational Platform',
    featured: true,
    images: {
      thumbnail: '/images/projects/comsim/learn.png',
      screenshots: [
        '/images/projects/comsim/learn.png',
        '/images/projects/comsim/quiz.png',
      ],
    },
    technologies: {
      frontend: ['React Native', 'Expo', 'TypeScript', 'JavaScript'],
      backend: ['Expo Router'],
      tools: ['Expo Linear Gradient', 'React Native Reanimated', 'React Native Gesture Handler', 'React Native SVG', 'Jest'],
    },
    features: [
      'Interactive Learning Modules - Comprehensive lessons on PC components (CPU, GPU, RAM, Motherboard, Storage, PSU)',
      'Simulation Mode - Build virtual PCs with realistic component selection and compatibility checking (Work in Progress - currently in development)',
      'Quiz & Assessment - Test knowledge with interactive quizzes and instant feedback',
      'Modern UI/UX - Clean, intuitive interface with smooth animations and transitions',
      'Component Browser - Explore different PC parts with detailed specifications',
      'Performance Estimation - Bottleneck analysis and performance optimization tips',
      'Progressive Learning - Difficulty levels adapting to user knowledge',
      'Visual Guides - Step-by-step assembly instructions with illustrations',
    ],
    challenges: [
      'Creating an intuitive UI for complex PC building concepts',
      'Implementing realistic component compatibility checking logic',
      'Managing component data and specifications efficiently',
      'Building smooth animations and transitions in React Native',
    ],
    solutions: [
      'Designed modular architecture with separate learning and simulation modules',
      'Implemented file-based routing with Expo Router for clean navigation',
      'Used React Native Reanimated for performant animations',
      'Created comprehensive component database with compatibility matrices',
    ],
    links: {
      github: 'https://github.com/jerwinagustin/ComSim',
      demo: 'https://github.com/jerwinagustin/ComSim/releases/latest/download/ComSim.apk',
    },
    date: 'January 2025 - April 2025',
    role: 'Mobile Developer',
    metrics: [
      { label: 'Status', value: 'First Project' },
      { label: 'Type', value: 'Educational App' },
      { label: 'Platform', value: 'Android' },
    ],
  },
  {
    id: '2',
    slug: 'loglife',
    title: 'LogLife',
    shortDescription: 'A comprehensive personal productivity application that seamlessly integrates diary journaling, intelligent reminder management, and real-time weather tracking.',
    fullDescription: 'LogLife is a comprehensive personal productivity application built with Flutter and powered by Firebase. It helps users organize their daily lives through an intuitive, feature-rich interface that combines diary journaling, smart reminders, and weather tracking in one unified mobile experience.',
    category: 'Mobile App',
    featured: true,
    images: {
      thumbnail: '/images/projects/loglife/homepage.jpg',
      screenshots: [
        '/images/projects/loglife/homepage.jpg',
        '/images/projects/loglife/loginpage.jpg',
      ],
    },
    technologies: {
      frontend: ['Flutter', 'Dart', 'Material Design'],
      backend: ['Firebase Authentication', 'Cloud Firestore', 'Firebase Realtime Database'],
      database: ['Firestore', 'Realtime Database'],
      tools: ['Google Sign-In', 'OpenWeatherMap API', 'Flutter Local Notifications', 'Geolocator', 'Lottie'],
    },
    features: [
      'Calendar-Based Journaling - Organize diary entries by date with intuitive calendar interface',
      'Smart Reminder System - Multi-tier notifications (1 hour, 30 minutes, exact time)',
      'Real-Time Weather Integration - Location-based forecasts with 7-day predictions',
      'Firebase Authentication - Secure email/password login and Google Sign-In',
      'Timezone Intelligence - Automatic device timezone detection',
      'Rich Text Entries - Create detailed notes with titles, genres/categories, and timestamps',
      'Animated Weather Icons - Lottie animations for various weather conditions',
      'CRUD Operations - Full create, read, update, and delete functionality',
      'Push Notifications - Alarm-style alerts with "Mark Done" quick actions',
      'Real-time Sync - All entries automatically sync with Firebase',
    ],
    challenges: [
      'Implementing multi-tier notification system across Android and iOS platforms',
      'Handling timezone calculations for reminders accurately',
      'Integrating multiple Firebase services (Auth, Firestore, Realtime DB) seamlessly',
      'Managing notification IDs to prevent platform conflicts',
    ],
    solutions: [
      'Used flutter_timezone and timezone packages for accurate time handling',
      'Implemented hashed notification IDs with offsets to prevent collisions',
      'Created modular architecture with separate service layers for each feature',
      'Wrapped all scheduling/cancellation in try/catch blocks for robust error handling',
    ],
    links: {
      github: 'https://github.com/jerwinagustin/PersonalApplication',
      demo: 'https://github.com/jerwinagustin/PersonalApplication/raw/main/build/app/outputs/apk/release/app-release.apk',
    },
    date: 'July 2025 - November 2025',
    role: 'Full-Stack Mobile Developer',
    metrics: [
      { label: 'Platform', value: 'Android' },
      { label: 'Architecture', value: 'Feature-based Modular' },
      { label: 'APK Size', value: '20MB' },
      { label: 'Project', value: 'Second Work' },
    ],
  },
  {
    id: '3',
    slug: 'expand',
    title: 'Expand',
    shortDescription: 'A modern, full-featured expense tracking web application that helps users manage monthly budgets, track expenses across categories, and visualize spending patterns.',
    fullDescription: 'Expand is a comprehensive expense tracking web application built with CodeIgniter 4 and MySQL. It provides users with powerful tools to manage their monthly budgets, track expenses across custom categories, and visualize spending patterns through an intuitive dashboard with real-time analytics.',
    category: 'Web Application',
    featured: true,
    images: {
      thumbnail: '/images/projects/expand/expanddashboard.png',
      screenshots: [
        '/images/projects/expand/expanddashboard.png',
        '/images/projects/expand/expandlogin.png',
      ],
    },
    technologies: {
      frontend: ['Bootstrap 5', 'JavaScript', 'AJAX', 'HTML5', 'CSS3', 'Boxicons'],
      backend: ['PHP 8.1+', 'CodeIgniter 4'],
      database: ['MySQL 8.0', 'MariaDB'],
      tools: ['Composer', 'Apache/Nginx', 'phpMyAdmin'],
    },
    features: [
      'Secure Authentication - Password hashing with PHP\'s password_hash() and session-based auth',
      'Monthly Balance Tracking - Set and track monthly budgets with real-time calculations',
      'Custom Categories - Create personalized expense categories with icon selection',
      'Budget Allocation - Set budgets for each category with spending tracking',
      'Quick Expense Entry - Fast recording with date selection and category assignment',
      'Visual Dashboard - Overview of spending patterns with charts and graphs',
      'Transaction History - Complete audit trail of all income and expenses',
      'Monthly Trends - Track expenses over time with 6-month view',
      'Dark/Light Mode - Toggle between themes with persistent preference',
      'Responsive Design - Mobile-friendly Bootstrap 5 layout',
      'CSRF Protection - Built-in CodeIgniter CSRF tokens for security',
      'Reports & Analytics - Category breakdown and budget vs. actual comparisons',
    ],
    challenges: [
      'Designing normalized database schema with proper foreign key relationships',
      'Implementing real-time balance updates across multiple tables',
      'Creating responsive UI that works seamlessly on mobile and desktop',
      'Ensuring security with SQL injection prevention and XSS protection',
    ],
    solutions: [
      'Used 5 normalized tables with cascading deletes for data integrity',
      'Implemented MVC architecture for clean separation of concerns',
      'Utilized CodeIgniter\'s Query Builder with parameter binding for security',
      'Created AJAX-powered dynamic content updates for smooth UX',
    ],
    links: {
      github: 'https://github.com/jerwinagustin/Expand',
    },
    date: 'October 2025 - November 2025',
    role: 'Full-Stack Web Developer',
    metrics: [
      { label: 'Database Tables', value: '5 Normalized' },
      { label: 'Lines of Code', value: '3000+' },
      { label: 'Architecture', value: 'MVC Pattern' },
      { label: 'Project', value: 'Third Work' },
    ],
  },
]

export const featuredProjects = projects.filter((project) => project.featured)
